In [1]:
#STEP 1 - IMPORT DATA

import pandas as pd

In [7]:
dataset = pd.read_csv("/Users/christophergbezo/Documents/PROJET_01/Speed Dating Data.csv", encoding="ISO-8859-1")
dataset.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [10]:
# Print the shape of dataset in the form of (#rows, #columns)
print(dataset.shape)

# Describe dataset's main statistics
print(dataset.describe(include="all"))

(8378, 195)
                iid           id       gender          idg       condtn  \
count   8378.000000  8377.000000  8378.000000  8378.000000  8378.000000
unique          NaN          NaN          NaN          NaN          NaN
top             NaN          NaN          NaN          NaN          NaN
freq            NaN          NaN          NaN          NaN          NaN
mean     283.675937     8.960248     0.500597    17.327166     1.828837
std      158.583367     5.491329     0.500029    10.940735     0.376673
min        1.000000     1.000000     0.000000     1.000000     1.000000
25%      154.000000     4.000000     0.000000     8.000000     2.000000
50%      281.000000     8.000000     1.000000    16.000000     2.000000
75%      407.000000    13.000000     1.000000    26.000000     2.000000
max      552.000000    22.000000     1.000000    44.000000     2.000000

               wave        round     position     positin1        order  ...  \
count   8378.000000  8378.000000  8378.000000  6532.000000  8378.000000  ...
unique          NaN          NaN          NaN          NaN          NaN  ...
top             NaN          NaN          NaN          NaN          NaN  ...
freq            NaN          NaN          NaN          NaN          NaN  ...
mean      11.350919    16.872046     9.042731     9.295775     8.927668  ...
std        5.995903     4.358458     5.514939     5.650199     5.477009  ...
min        1.000000     5.000000     1.000000     1.000000     1.000000  ...
25%        7.000000    14.000000     4.000000     4.000000     4.000000  ...
50%       11.000000    18.000000     8.000000     9.000000     8.000000  ...
75%       15.000000    20.000000    13.000000    14.000000    13.000000  ...
max       21.000000    22.000000    22.000000    22.000000    22.000000  ...

            attr3_3      sinc3_3     intel3_3       fun3_3       amb3_3  \
count   3974.000000  3974.000000  3974.000000  3974.000000  3974.000000
unique          NaN          NaN          NaN          NaN          NaN
top             NaN          NaN          NaN          NaN          NaN
freq            NaN          NaN          NaN          NaN          NaN
mean       7.240312     8.093357     8.388777     7.658782     7.391545
std        1.576596     1.610309     1.459094     1.744670     1.961417
min        2.000000     2.000000     3.000000     2.000000     1.000000
25%        7.000000     7.000000     8.000000     7.000000     6.000000
50%        7.000000     8.000000     8.000000     8.000000     8.000000
75%        8.000000     9.000000     9.000000     9.000000     9.000000
max       12.000000    12.000000    12.000000    12.000000    12.000000

            attr5_3      sinc5_3     intel5_3       fun5_3       amb5_3
count   2016.000000  2016.000000  2016.000000  2016.000000  2016.000000
unique          NaN          NaN          NaN          NaN          NaN
top             NaN          NaN          NaN          NaN          NaN
freq            NaN          NaN          NaN          NaN          NaN
mean       6.810020     7.615079     7.932540     7.155258     7.048611
std        1.507341     1.504551     1.340868     1.672787     1.717988
min        2.000000     2.000000     4.000000     1.000000     1.000000
25%        6.000000     7.000000     7.000000     6.000000     6.000000
50%        7.000000     8.000000     8.000000     7.000000     7.000000
75%        8.000000     9.000000     9.000000     8.000000     8.000000
max       10.000000    10.000000    10.000000    10.000000    10.000000

[11 rows x 195 columns]

In [ ]:
# VoilÃ  oÃ¹ je me suis arrÃªtÃ©